name: AndroidBuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore to project root
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > RealTimeKeystore.jks

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Upload Unit Test Report even if tests fail
      - name: Upload Unit Test Report
        if: always() # Ensures this runs even if previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/

      - name: Build Debug APK
        run: ./gradlew assembleDebug -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
            --app "1:1027610363585:android:bbacf92a597fcd151f3640" \
            --release-notes-file app/release_notes.txt \
            --testers-file app/testers.txt   

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: RealScan.apk
          path: app/build/outputs/apk/debug/app-debug.apk